In [1]:
import pandas as pd
import matplotlib.pylab as plt

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from pathlib import Path
import heapq
from collections import defaultdict

In [6]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: numpy>=1.16.2 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (1.21.5)
Requirement already satisfied: scipy>=1.2.1 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: joblib>=0.13.2 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: setuptools in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (61.2.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (3.5.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\vamshi krishna\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.21.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
fp_df = pd.read_csv('Faceplate.csv')
fp_df.set_index('Transaction', inplace=True)
fp_df

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0
6              0      1     1       0      0       0
7              1      0     1       0      0       0
8              1      1     1       0      1       0
9              1      1     1       0      0       0
10             0      0     0       0      0       1

In [4]:
itemsets = apriori(fp_df, min_support=0.2, use_colnames=True)
itemsets

C:\Users\Vamshi Krishna\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (Red, White)
6       0.4          (Blue, Red)
7       0.2         (Red, Green)
8       0.4        (Blue, White)
9       0.2      (White, Orange)
10      0.2       (White, Green)
11      0.2   (Blue, Red, White)
12      0.2  (Red, White, Green)

In [5]:
rules = association_rules(itemsets, metric='confidence', min_threshold=0.5)
rules.sort_values(by=['lift'], ascending=False).head(6)
print(rules.sort_values(by=['lift'], ascending=False)
.drop(columns=['antecedent support', 'consequent support', 'conviction'])
.head(6))

       antecedents   consequents  support  confidence      lift  leverage
12    (Red, White)       (Green)      0.2         0.5  2.500000      0.12
15         (Green)  (Red, White)      0.2         1.0  2.500000      0.12
4          (Green)         (Red)      0.2         1.0  1.666667      0.08
14  (White, Green)         (Red)      0.2         1.0  1.666667      0.08
7         (Orange)       (White)      0.2         1.0  1.428571      0.06
8          (Green)       (White)      0.2         1.0  1.428571      0.06

In [6]:
rules[[len(c) == 1 for c in rules.consequents]].sort_values(by=['lift'],
ascending=False).head(6)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
12,"(Red, White)",(Green),0.4,0.2,0.2,0.5,2.500000,0.12,1.6
4,(Green),(Red),0.2,0.6,0.2,1.0,1.666667,0.08,inf
14,"(White, Green)",(Red),0.2,0.6,0.2,1.0,1.666667,0.08,inf
7,(Orange),(White),0.2,0.7,0.2,1.0,1.428571,0.06,inf
8,(Green),(White),0.2,0.7,0.2,1.0,1.428571,0.06,inf
13,"(Red, Green)",(White),0.2,0.7,0.2,1.0,1.428571,0.06,inf